### ISSUE TITLE
Cannot add a second dependency to the same component

### ISSUE THREAD

**Issue by mikkelhegn** [karthik2804/spin-deps#15]
When trying to add a second dependency to a component, I receive the following error:

```
Error: failed to merge package `root:component` into existing copy

Caused by:
    0: failed to merge world `dependency-world`
    1: world contains different number of imports than expected
```

I have tried first adding on, then the other and also the other way around. Each individual dependency is added fine, but if there is one already and another is added, the above error happens.

**Comment by karthik2804** [comment]
It is the same issue as #9. This is currently blocked on https://github.com/bytecodealliance/wasm-tools/issues/1897

**Comment by mikkelhegn** [comment]
Oh sorry, missed that the second use-case was adding a second component. Feel free to close.
